import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { getServerSession } from "next-auth";
import SessionProvider from "@/app/components/SessionProvider";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import NavMenu from "./components/NavMenu";
import { DateProvider } from "./context/DateContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GoFit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      {/* <head>
        <ColorSchemeScript />
      </head> */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider>
          <DateProvider>
            <SessionProvider session={session}>
                <NavMenu />
                {children}
            </SessionProvider>
          </DateProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
